run:
  timeout: 3m
  tests: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
